defaults:
  - _self_
  - model: model
  - dataset: toy     # loads dataset/toy.yaml

checkpoint_path: "results_training"
angle_train_path: training/angles.txt
lr_train: 0.0003
num_epochs: 100
batch_size: 1
log_every_n_steps: 800
check_val_every_n_epoch: 10
num_workers: 8


roi_res: [1080, 1920]
use_mask: false
mask_threshold: 1/256

# Data loader parameters
dataset_size: 1000
data_shuffle: true
data_mask_target: false